const a = [
  {
    title: "BCG X Lead Data Scientist",
    company: "Boston Consulting Group",
    location: "4.2",
    rating: "4.2",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "Lead Data Scientist (GenAI)",
    company: "Boston Consulting Group",
    location: "4.2",
    rating: "4.2",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "Data Scientist - Matching Science",
    company: "Indeed",
    location: "4.3",
    rating: "4.3",
    salary: "₹32,00,000 - ₹48,00,000 a year",
    job_type: "Full-time",
  },
  {
    title: "Senior Data Scientist- 24010127",
    company: "MoneyGram",
    location: "3.7",
    rating: "3.7",
    salary: "N/A",
    job_type: "Full-time",
  },
  {
    title: "Data Scientist – AI/ML",
    company: "Mastercard",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "Full-time",
  },
  {
    title: "Data Scientist",
    company: "Lowe's",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "Full-time",
  },
  {
    title: "Data Scientist",
    company: "Virtusa",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "Full-time",
  },
  {
    title: "Data Scientist (m/f/d)",
    company: "Codepan GmbH",
    location: "Remote",
    rating: "Remote",
    salary: "₹30,00,000 - ₹35,00,000 a year",
    job_type: "N/A",
  },
  {
    title: "Jr. Data Scientist",
    company: "AkzoNobel",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "Data Scientist (ML)",
    company: "Courtroom Insight",
    location: "Remote",
    rating: "Remote",
    salary: "₹6,00,000 - ₹12,00,000 a year",
    job_type: "Full-time",
  },
  {
    title: "Data Scientist_ PowerBI",
    company: "Yash Technologies",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "Staff Engineer - Data Scientist",
    company: "Freshworks",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "Data Scientist",
    company: "DocuSign",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "Machine Learning Data Science",
    company: "Tata Consultancy Services",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "Data Scientist - I",
    company: "BigShyft",
    location: "Remote",
    rating: "Remote",
    salary: "₹10,00,000 - ₹27,50,000 a year",
    job_type: "N/A",
  },
];
