const a = [
  {
    title: "N/A",
    company: "Ventra Health, Inc.",
    location: "Remote",
    rating: "3.3",
    salary: "Full-time",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "Ventra Health, Inc.",
    location: "Remote",
    rating: "3.3",
    salary: "Full-time",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "Indeed",
    location: "Remote",
    rating: "4.3",
    salary: "₹49,60,000 - ₹74,40,000 a year",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "Indeed",
    location: "Remote",
    rating: "4.3",
    salary: "₹32,00,000 - ₹48,00,000 a year",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "Codepan GmbH",
    location: "Remote",
    rating: "N/A",
    salary: "₹30,00,000 - ₹35,00,000 a year",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "Courtroom Insight",
    location: "Remote",
    rating: "N/A",
    salary: "₹6,00,000 - ₹12,00,000 a year",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "www.24SevenCommerce.com",
    location: "Remote",
    rating: "N/A",
    salary: "₹10,000 - ₹50,000 a month",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "Brain Links and resources pvt",
    location: "Remote",
    rating: "N/A",
    salary: "₹8,27,051.50 - ₹13,62,179.88 a year",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "Indium Software Inc.",
    location: "Remote",
    rating: "N/A",
    salary: "₹22,00,000 - ₹28,00,000 a year",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "Virtusa",
    location: "Remote",
    rating: "N/A",
    salary: "Full-time",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "Tata Consultancy Services",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "Salfom technologies",
    location: "Remote",
    rating: "N/A",
    salary: "Up to ₹15,00,000 a year",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "Boston Consulting Group",
    location: "Remote",
    rating: "4.2",
    salary: "Full-time",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "AkzoNobel",
    location: "Remote",
    rating: "N/A",
    salary: "Permanent",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "Philips",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
];
