const a = [
  {
    title: "Data Scientist",
    company: "Ventra Health, Inc.",
    location: "3.3",
    rating: "3.3",
    salary: "N/A",
    job_type: "Full-time",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "Data Scientist - Matching Science",
    company: "Indeed",
    location: "4.3",
    rating: "4.3",
    salary: "₹32,00,000 - ₹48,00,000 a year",
    job_type: "Full-time",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "Data Scientist (m/f/d)",
    company: "Codepan GmbH",
    location: "Remote",
    rating: "Remote",
    salary: "₹30,00,000 - ₹35,00,000 a year",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "Data Scientist (ML)",
    company: "Courtroom Insight",
    location: "Remote",
    rating: "Remote",
    salary: "₹6,00,000 - ₹12,00,000 a year",
    job_type: "Full-time",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "Data Scientist",
    company: "Virtusa",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "Full-time",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "Data Scientist",
    company: "www.24SevenCommerce.com",
    location: "Remote",
    rating: "Remote",
    salary: "₹10,000 - ₹50,000 a month",
    job_type: "Full-time",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "Data Scientist",
    company: "Brain Links and resources pvt",
    location: "Remote",
    rating: "N/A",
    salary: "₹8,27,051.50 - ₹13,62,179.88 a year",
    job_type: "Full-time",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "Data Scientist",
    company: "Indium Software Inc.",
    location: "Remote",
    rating: "N/A",
    salary: "₹22,00,000 - ₹28,00,000 a year",
    job_type: "Full-time",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "AI Developer NLP , Deep learning(Work FROM Home)",
    company: "Salfom technologies",
    location: "Remote",
    rating: "Remote",
    salary: "Up to ₹15,00,000 a year",
    job_type: "Full-time",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "Machine Learning Data Science",
    company: "Tata Consultancy Services",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "Data Scientist Level_1",
    company: "Michelin",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "Full-time",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "Data and Analytics - Associate",
    company: "JPMorgan Chase & Co",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "Full-time",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "Analyst, Geo Analytics - X Delivery",
    company: "Boston Consulting Group",
    location: "4.2",
    rating: "4.2",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "Data Scientist Engineer (Remote) - Microsoft Contract India",
    company: "Volga Partners",
    location: "Remote",
    rating: "Remote",
    salary: "₹25,00,000 - ₹32,00,000 a year",
    job_type: "Full-time",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "Data Scientist",
    company: "SVPNC TECHNOLOGIES",
    location: "Remote",
    rating: "N/A",
    salary: "₹25,00,000 - ₹45,00,000 a year",
    job_type: "Full-time",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "N/A",
    company: "N/A",
    location: "Remote",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
];
