const a = [
  {
    title: "BCG X Lead Data Scientist",
    company: "Boston Consulting Group",
    location: "N/A",
    rating: "4.2",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "Data Scientist",
    company: "Ventra Health, Inc.",
    location: "N/A",
    rating: "3.3",
    salary: "N/A",
    job_type: "Full-time",
  },
  {
    title: "Senior Data Scientist",
    company: "Ventra Health, Inc.",
    location: "N/A",
    rating: "3.3",
    salary: "N/A",
    job_type: "Full-time",
  },
  {
    title: "Data Scientist (ML)",
    company: "Courtroom Insight",
    location: "N/A",
    rating: "N/A",
    salary: "₹6,00,000 - ₹12,00,000 a year",
    job_type: "Full-time",
  },
  {
    title: "Data Scientist (m/f/d)",
    company: "Codepan GmbH",
    location: "N/A",
    rating: "N/A",
    salary: "₹30,00,000 - ₹35,00,000 a year",
    job_type: "N/A",
  },
  {
    title: "Data scientist/Github /Azure Databricks",
    company: "CareAtor technologies",
    location: "N/A",
    rating: "N/A",
    salary: "₹20,85,596.75 a year",
    job_type: "Full-time",
  },
  {
    title: "DATA & APPLIED SCIENTIST II",
    company: "Microsoft",
    location: "N/A",
    rating: "N/A",
    salary: "N/A",
    job_type: "Full-time",
  },
  {
    title: "Data Scientist",
    company: "Indium Software Inc.",
    location: "N/A",
    rating: "N/A",
    salary: "₹22,00,000 - ₹28,00,000 a year",
    job_type: "Full-time",
  },
  {
    title: "Data Scientist",
    company: "www.24SevenCommerce.com",
    location: "N/A",
    rating: "N/A",
    salary: "₹10,000 - ₹50,000 a month",
    job_type: "Full-time",
  },
  {
    title: "Data Scientist",
    company: "Brain Links and resources pvt",
    location: "N/A",
    rating: "N/A",
    salary: "₹8,27,051.50 - ₹13,62,179.88 a year",
    job_type: "Full-time",
  },
  {
    title: "AI Developer NLP , Deep learning(Work FROM Home)",
    company: "Salfom technologies",
    location: "N/A",
    rating: "N/A",
    salary: "Up to ₹15,00,000 a year",
    job_type: "Full-time",
  },
  {
    title: "Data Scientist",
    company: "Virtusa",
    location: "N/A",
    rating: "N/A",
    salary: "N/A",
    job_type: "Full-time",
  },
  {
    title: "Machine Learning Data Science",
    company: "Tata Consultancy Services",
    location: "N/A",
    rating: "N/A",
    salary: "N/A",
    job_type: "N/A",
  },
  {
    title: "Data Scientist",
    company: "Indium Software Inc.",
    location: "N/A",
    rating: "N/A",
    salary: "₹10,00,000 - ₹18,00,000 a year",
    job_type: "Full-time",
  },
  {
    title: "Data Scientist Level_1",
    company: "Michelin",
    location: "N/A",
    rating: "N/A",
    salary: "N/A",
    job_type: "Full-time",
  },
];
